# Generated by Django 4.1.4 on 2022-12-23 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('color', models.IntegerField()),
                ('shadow', models.IntegerField()),
                ('shadowColor', models.IntegerField()),
                ('border', models.IntegerField()),
                ('creators', models.TextField()),
                ('postNumber', models.IntegerField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consonant', models.CharField(max_length=10)),
                ('contents', models.TextField()),
                ('likes', models.IntegerField()),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='dictionary.dictionary')),
            ],
        ),
    ]
