# Generated by Django 4.1.4 on 2022-12-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_alter_dictionary_postnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionary',
            old_name='title',
            new_name='firstName',
        ),
    ]
