# Generated by Django 4.1.4 on 2022-12-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_rename_title_dictionary_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='postNumber',
            field=models.IntegerField(null=True),
        ),
    ]
