# Generated by Django 4.1.5 on 2023-01-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_alter_dictionary_postnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='color',
            field=models.CharField(max_length=100),
        ),
    ]
