# Generated by Django 4.0.4 on 2023-01-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_accounts_email_accounts_firstname'),
        ('dictionary', '0006_alter_dictionary_postnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='posts', to='accounts.accounts'),
        ),
    ]
