# Generated by Django 4.0.4 on 2023-01-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_accounts_email_accounts_firstname'),
        ('dictionary', '0007_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.PositiveBigIntegerField(default=0, verbose_name='LIKE'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post', to='accounts.accounts'),
        ),
    ]
