# Generated by Django 4.0.4 on 2023-01-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_post_like_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='nickname',
            field=models.CharField(default='사람', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
