# Generated by Django 4.0.4 on 2023-01-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_remove_post_likes_post_nickname_alter_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nickname',
            field=models.CharField(default='행인', max_length=30),
        ),
    ]
