# Generated by Django 4.0.4 on 2023-01-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_alter_post_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stack',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
