# Generated by Django 4.1.4 on 2022-12-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='postNumber',
            field=models.IntegerField(blank=True),
        ),
    ]
