# Generated by Django 4.1.5 on 2023-02-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_userid_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userNumber',
            field=models.IntegerField(default=0),
        ),
    ]
