# Generated by Django 4.1.4 on 2022-12-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='email',
        ),
        migrations.AddField(
            model_name='accounts',
            name='firstName',
            field=models.CharField(default='', max_length=30),
        ),
    ]
