# Generated by Django 4.0.4 on 2023-02-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_post_stacked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='stacked',
        ),
        migrations.AddField(
            model_name='dictionary',
            name='stacked',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
